name: Deploy Stacks to Production VM

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # This step connects to your server and runs the deployment script
      - name: SSH to VM and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # --- This entire script runs on YOUR server ---

            # 1. Navigate to your project directory and pull changes
            cd ~/autom8
            echo "Pulling latest code..."
            git pull origin master
            
            echo "Changes detected in application files. Preparing and deploying autom8 stack..."
            chmod +x ./deploy-prep.sh
            ./deploy-prep.sh
            sudo docker stack deploy --with-registry-auth -c docker-stack.yml autom8
          

            # --- Final Cleanup ---
            echo "Pruning old images..."
            chmod +x ./clear-registry.sh
            sudo ./clear-registry.sh
            sudo docker image prune -af
            echo "âœ… Deployment checks complete!"